import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { robotoFlex } from "./font";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex w-full h-screen">
        <Sidebar />
        <div className={`${robotoFlex.className} antialiased home_content dark:bg-zinc-800 text-white`}>
          {children}
        </div>
      </body>
    </html>
  );
}
